# frozen_string_literal: true

InertiaI18n.configure do |config|
  # Source directories for your frontend YAML files.
  # `shared` holds keys used by both the frontend and Rails (e.g. activerecord
  # attribute labels) so they're defined once and stay in sync automatically.
  config.source_paths = [
    Rails.root.join("config/locales/frontend"),
    Rails.root.join("config/locales/shared")
  ]

  # Target path for generated i18next JSON files
  config.target_path = Rails.root.join("app/javascript/locales")

  # Locales to process — uses I18n.available_locales by default (set in config/application.rb)

  # YAML file pattern to match
  config.source_pattern = "**/*.{yml,yaml}"

  # Paths to scan for translation usage
  config.scan_paths = [
    "app/javascript/**/*.{js,ts,vue}"
  ]

  # Interpolation conversion (Rails %{var} -> i18next {{var}})
  config.interpolation = {from: "%{", to: "{{"}

  # Dynamic key patterns (prefix => description)
  # Keys matching these prefixes won't be marked as unused
  config.dynamic_patterns = {
    # "status." => "Dynamic status keys"
  }

  # Dynamic keys (prefix => array of possible values)
  # These keys will be automatically expanded and checked for existence
  config.dynamic_keys = {
    # "table.filters." => ["show_discarded"]
  }

  # Keys to ignore during unused check
  # "common" namespace is generated by inertia_i18n:install as sample data
  config.ignore_unused = []

  # Keys to ignore during missing check
  config.ignore_missing = []
end
