// DO NOT MODIFY: This file was automatically generated by `just fixtures`.

import type { Group } from "@/types"
import { groupFactory } from "../factories"

const liceo = {
  id: 1,
  name: "Liceo",
  people: [
    {
      id: 1,
      firstName: "Camillo",
      lastName: "Visini",
      favorite: false,
      birthdayDay: 17,
      birthdayMonth: 8,
      birthdayYear: 1994,
      name: "Camillo Visini",
      age: 31,
      birthday: "1994-08-17",
    },
  ],
} satisfies Group

export default {
  liceo: groupFactory.build(liceo),
} satisfies Record<string, Group>
