// DO NOT MODIFY: This file was automatically generated by `just fixtures`.

import type { Note } from "@/types"
import { noteFactory } from "../factories"

const camilloCall = {
  id: 1,
  title: "Call",
  body: "Discussed the roadmap for next quarter.",
  createdAt: "2025-01-01T00:00:00.000Z",
} satisfies Note

export default {
  camilloCall: noteFactory.build(camilloCall),
} satisfies Record<string, Note>
