// DO NOT MODIFY: This file was automatically generated by `just fixtures`.

import type { Person } from "@/types"
import { personFactory } from "../factories"

const camillo = {
  id: 1,
  firstName: "Camillo",
  lastName: "Visini",
  favorite: false,
  birthdayDay: 17,
  birthdayMonth: 8,
  birthdayYear: 1994,
  name: "Camillo Visini",
  age: 31,
  birthday: "1994-08-17",
} satisfies Person

export default {
  camillo: personFactory.build(camillo),
} satisfies Record<string, Person>
