// DO NOT MODIFY: This file was automatically generated by `just fixtures`.

import type { User } from "@/types"
import { userFactory } from "../factories"

const camillo = {
  id: 1,
  emailAddress: "c.visini@gmail.com",
} satisfies User

export default {
  camillo: userFactory.build(camillo),
} satisfies Record<string, User>
