// Typelizer digest 55d77ce9e46f17863686eafe84e7d89e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /groups/:group_id/group_memberships */
  create: (
    params: { groupId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/groups/:group_id/group_memberships', params, options),
    method: 'post',
  }),

  /** DELETE /groups/:group_id/group_memberships/:id */
  destroy: (
    params: { groupId: string | number; id: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/groups/:group_id/group_memberships/:id', params, options),
    method: 'delete',
  }),
}
