// Typelizer digest dc090ce864f1c57ba82bb7117c25b0ac
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /groups */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/groups', {}, options),
    method: 'get',
  }),

  /** POST /groups */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/groups', {}, options),
    method: 'post',
  }),

  /** GET /groups/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/groups/new', {}, options),
    method: 'get',
  }),

  /** GET /groups/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/groups/:id/edit', params, options),
    method: 'get',
  }),

  /** GET /groups/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/groups/:id', params, options),
    method: 'get',
  }),

  /** PATCH /groups/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/groups/:id', params, options),
    method: 'patch',
  }),
}
