// Typelizer digest 73a48c30cfb2524504a1e723c63142bd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /groups */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/groups', {}, options),
    method: 'get',
  }),
}
