// Typelizer digest f61853b574131787aeb3ceef826454df
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as groups } from './GroupsController'
export { default as pages } from './PagesController'
export { default as people } from './PeopleController'

import _pages from './PagesController'
import _people from './PeopleController'

export const home = _pages.home
export const person = _people.show
export const root = _pages.root
