// Typelizer digest 75cf7d8e315b27bc2f9bb7fa8f733504
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as pages } from './PagesController'
export { default as people } from './PeopleController'

import _pages from './PagesController'
import _people from './PeopleController'

export const home = _pages.home
export const person = _people.show
export const root = _pages.root
