// Typelizer digest 8292a1da3836a67576c771faaabf9a43
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as pages } from './PagesController'

import _pages from './PagesController'

export const home = _pages.home
export const root = _pages.root
