// Typelizer digest 2bb9acf99d1c44cc3778d16c57cfe98b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /people/:person_id/notes */
  create: (
    params: { personId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/people/:person_id/notes', params, options),
    method: 'post',
  }),

  /** GET /people/:person_id/notes/:id/edit */
  edit: (
    params: { personId: string | number; id: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/people/:person_id/notes/:id/edit', params, options),
    method: 'get',
  }),

  /** PATCH /people/:person_id/notes/:id */
  update: (
    params: { personId: string | number; id: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/people/:person_id/notes/:id', params, options),
    method: 'patch',
  }),
}
