// Typelizer digest baed5099ba01e503f183fd3601f60cd8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /people */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/people', {}, options),
    method: 'get',
  }),

  /** GET /people/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/people/:id', params, options),
    method: 'get',
  }),
}
