// Typelizer digest 8ae67fcc32902298906a237f65b880fc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /people */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/people', {}, options),
    method: 'get',
  }),

  /** POST /people */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/people', {}, options),
    method: 'post',
  }),

  /** GET /people/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/people/new', {}, options),
    method: 'get',
  }),

  /** GET /people/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/people/:id/edit', params, options),
    method: 'get',
  }),

  /** GET /people/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/people/:id', params, options),
    method: 'get',
  }),

  /** PATCH /people/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/people/:id', params, options),
    method: 'patch',
  }),
}
