// Typelizer digest 21179e8fac8f2ba45b2b5d3c6f4ee77e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Group} from '@/types'

type GroupsNew = {
  group: Group;
}

export default GroupsNew;
