// Typelizer digest a0bb5d56cdac695eb29708a3482ddaa9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {GroupMembership} from '@/types'

type Group = {
  id: number;
  name: string;
  groupMemberships: Array<GroupMembership>;
}

export default Group;
