// Typelizer digest 6c0117a3685634694b673752a306840c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Person} from '@/types'

type Group = {
  id: number;
  name: string;
  people: Array<Person>;
}

export default Group;
