// Typelizer digest 32d7f2c195658045c71c2abf9a7b549e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Group} from '@/types'

type GroupsEdit = {
  group: Group;
}

export default GroupsEdit;
