// Typelizer digest 9d5ee727c317d6f59d6e75f56658d435
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Group, Person} from '@/types'

type GroupsShow = {
  group: Group;
  availablePeople: Array<Person>;
}

export default GroupsShow;
