// Typelizer digest 0fedf91296d7c2ce6845a5aafa3bf4c4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Group} from '@/types'

type GroupsIndex = {
  groups: Array<Group>;
}

export default GroupsIndex;
