// Typelizer digest 66fd7af45f40fcbc366dfed4ce7eeac8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Person} from '@/types'

type GroupMembership = {
  id: number;
  person: Person;
}

export default GroupMembership;
