// Typelizer digest 5d969581f51f131c46c81d8576d7d8d2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Note = {
  id: number;
  title: string;
  body: string;
  createdAt: string;
}

export default Note;
