// Typelizer digest 77182797c2782ebbd44ed50b6f9788a1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Note, Person} from '@/types'

type NotesEdit = {
  note: Note;
  person: Person;
}

export default NotesEdit;
