// Typelizer digest 8581e15312201c0b549e4750bc944c86
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {User} from '@/types'

type PagesHome = {
  currentUser: User;
}

export default PagesHome;
