// Typelizer digest 57635aab2cd66cf7700b46568323acc7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {User, Person} from '@/types'

type PagesHome = {
  currentUser: User;
  upcomingBirthdays: Array<Person>;
}

export default PagesHome;
