// Typelizer digest c86179101f2e13128583ef2620c49c23
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Person, Note} from '@/types'

type PeopleShow = {
  person: Person;
  notes: Array<Note>;
}

export default PeopleShow;
