// Typelizer digest 7ca9b6fdf0325fa2dd43fa72bc4b1cb3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Person} from '@/types'

type PeopleEdit = {
  person: Person;
}

export default PeopleEdit;
