// Typelizer digest 49873e2e66d654805ee9a1181a9e1605
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Person} from '@/types'

type PeopleNew = {
  person: Person;
}

export default PeopleNew;
