// Typelizer digest 3431986bf85ce68225af47df6cda765e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Person} from '@/types'

type PeopleShow = {
  person: Person;
}

export default PeopleShow;
