// Typelizer digest f78e8f89872a3fc958572490338b5efe
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Person} from '@/types'

type PeopleIndex = {
  people: Array<Person>;
}

export default PeopleIndex;
