// Typelizer digest 275a5585bfcad2c6780eb5cc8603cb06
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Person = {
  id: number;
  firstName: string;
  lastName: string;
  favorite: boolean;
  birthdayDay: number | null;
  birthdayMonth: number | null;
  birthdayYear: number | null;
  name: string;
  age: number | null;
  birthday: string | null;
}

export default Person;
