// Typelizer digest 181d90ee928341fcc8faaf8a7c9dcf66
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  emailAddress: string;
}

export default User;
