# frozen_string_literal: true

module FrontendFixtures
  STUB_TIMESTAMP = "2025-01-01T00:00:00.000Z"
  TIMESTAMP_KEYS = ["createdAt", "updatedAt"].freeze

  class Exporter
    # Seeded ApplicationRecord classes to skip when exporting frontend fixtures,
    # e.g. because there's no corresponding frontend resource/type for them.
    SKIPPED_MODELS = ["GroupMembership"].freeze

    def run
      ActiveRecord::Tasks::DatabaseTasks.truncate_all
      reset_sequences
      Rails.application.load_seed

      models.map { |model| export_fixture(model) }
    end

    private

    def reset_sequences
      connection = ActiveRecord::Base.connection
      connection
        .execute("SELECT sequence_name FROM information_schema.sequences WHERE sequence_schema = 'public'")
        .each do |row|
          sequence_name = connection.quote_table_name(row["sequence_name"])
          connection.execute("ALTER SEQUENCE #{sequence_name} RESTART WITH 1")
        end
    end

    def models
      Rails.root.glob("db/seeds/*.rb").filter_map do |path|
        File.basename(path, ".rb").classify.safe_constantize
      end.select { |const| const.is_a?(Class) && const < ApplicationRecord && !SKIPPED_MODELS.include?(const.name) }
    end

    def export_fixture(model)
      table = model.name.tableize.to_sym

      stored = Oaken::Seeds.public_send(table)
      if stored.labels.empty?
        raise "#{model} has a seed file but no labeled records were loaded — add `Oaken.seed :#{table}` to db/seeds.rb"
      end

      resource_name = "#{model.name}Resource"
      resource = resource_name.safe_constantize or
        raise "#{resource_name} not found — create it before exporting fixtures for #{model}"
      ts_type = model.name
      types_import = Typelizer.configuration.types_import_path
      factory_name = "#{model.name.camelize(:lower)}Factory"
      output_path = Rails.root.join("app/javascript/test/fixtures/#{table.to_s.camelize(:lower)}.ts")

      fixtures = stored.labels.each_with_object({}) do |(label, id), result|
        attrs = serialize_seeded_record(stored.type, id, resource)
        result[label.to_s.camelize(:lower)] = stub_timestamps(attrs)
      end

      File.write(output_path, generate_ts(fixtures, ts_type:, types_import:, factory_name:))
      output_path
    end

    def serialize_seeded_record(model, id, resource)
      return JSON.parse(resource.new(model.find(id)).serialize) unless model.column_names.include?("account_id")

      record = ActsAsTenant.without_tenant { model.find(id) }
      ActsAsTenant.with_tenant(record.account) do
        JSON.parse(resource.new(record).serialize)
      end
    end

    def stub_timestamps(attrs)
      attrs.tap do |result|
        TIMESTAMP_KEYS.each { |key| result[key] = STUB_TIMESTAMP if result.key?(key) }
      end
    end

    def generate_ts(fixtures, ts_type:, types_import:, factory_name:)
      lines = []
      lines << "// DO NOT MODIFY: This file was automatically generated by `just fixtures`."
      lines << ""
      lines << "import type { #{ts_type} } from \"#{types_import}\""
      lines << "import { #{factory_name} } from \"../factories\""
      lines << ""

      fixtures.each do |label, attrs|
        lines << "const #{label} = {"
        attrs.each { |key, value| lines << "  #{key}: #{ts_literal(value)}," }
        lines << "} satisfies #{ts_type}"
        lines << ""
      end

      lines << "export default {"

      fixtures.each_key do |label|
        lines << "  #{label}: #{factory_name}.build(#{label}),"
      end

      lines << "} satisfies Record<string, #{ts_type}>"
      lines << ""

      lines.join("\n")
    end

    def ts_literal(value)
      case value
      when NilClass then "null"
      when TrueClass then "true"
      when FalseClass then "false"
      when Integer, Float then value.to_s
      when String then "\"#{value.gsub("\\", "\\\\\\\\").gsub('"', '\\"')}\""
      when Array then "[#{value.map { ts_literal(it) }.join(", ")}]"
      when Hash then "{ #{value.map { |k, v| "#{k}: #{ts_literal(v)}" }.join(", ")} }"
      else "\"#{value}\""
      end
    end
  end
end
